server:
    port: 9091
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/forFirstSpringProject
        username: postgres
        password: postgresmaster